### ISSUE TITLE
Incorrect term translation in checkio-mission-elementary-unpack/translations/ru/info/task_description.html

### ISSUE THREAD

**Issue by anton85bk** [oduvan/checkio-mission-elementary-unpack#15]
Line "Ваше задание здесь создать функцию, которая получает массив(tuple)"

Term "tuple" in Russian are "кортеж", the word "массив" goes for "array".

I think it's very critical not missmatch terms, especially in learning guides.

**Comment by oduvan** [comment]
thanks, fixed
